# Generated by Django 3.0.4 on 2020-03-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200328_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.CharField(choices=[('Sampa', 'São Paulo'), ('Rio', 'Rio de Janeiro'), ('Santos', 'Santos')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
