# Generated by Django 3.0.5 on 2020-04-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_evento_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='local',
            field=models.CharField(blank=True, choices=[('Sampa', 'São Paulo'), ('Rio', 'Rio de Janeiro'), ('Santos', 'Santos')], max_length=50, null=True),
        ),
    ]
